Repository canada-ca/micro-acquisition, pull requests merged in 2021-07, with the labels that each got.

#215 Add calendar + strong
  _includes/opportunitiesTable.md
Labels: enhancement

#207 Add email to security disclosure
  SECURITY.md
Labels: bug

#216 Accessibility documents
  _data/i18n/general.yml
  _pages/en/user-guide.md
  _pages/fr/guide-utilisateur.md
Labels: accessibility

#217 Change underlines to span with arial label
  _pages/en/terms.md
  _pages/fr/termes.md
Labels: accessibility

#218 Add overflow override for paragraphs
  _pages/en/index.md
  _pages/fr/index.md
  assets/css/style.css
Labels: accessibility

#229 fix broken link in the french user guide
  _pages/fr/guide-utilisateur.md
Labels: accessibility
